name: github-actions/build
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run test
        run: yarn test
        env:
          CI: true
          AUTH_SERVICE_HOST: ${{ secrets.AUTH_SERVICE_HOST }}
