name: github-actions/build
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('yarn.lock') }}

      - name: Install packages
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run test
        run: yarn test:report
        env:
          CI: true
          AUTH_SERVICE_HOST: ${{ secrets.AUTH_SERVICE_HOST }}

      - uses: izhangzhihao/delete-comment@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

      - name: test result
        run: cat ./test-results.json
        if: always()

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: test-results
          name: JEST Tests
          path: ${{ github.workspace }}/test-results.json
          reporter: mocha-json
